# Default values for vue-skeleton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: ewocker
  pullPolicy: Always
  containerPort: 4000

service:
  type: ClusterIP
  port: 80

app:
  name: vue-skeleton
